// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAagTBxBMR1sQ7LL16UrT3wsNWr5CNZujc',
    appId: '1:64654885784:web:db5a10442ed920739ba1ed',
    messagingSenderId: '64654885784',
    projectId: 'expenses-app-a4b6b',
    authDomain: 'expenses-app-a4b6b.firebaseapp.com',
    storageBucket: 'expenses-app-a4b6b.firebasestorage.app',
    measurementId: 'G-T582322NH0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPOYa6anIcq7dXYkcSXKLrDpFiCsOypTg',
    appId: '1:64654885784:ios:b0ea577dde19a4819ba1ed',
    messagingSenderId: '64654885784',
    projectId: 'expenses-app-a4b6b',
    storageBucket: 'expenses-app-a4b6b.firebasestorage.app',
    iosBundleId: 'com.example.expensesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPOYa6anIcq7dXYkcSXKLrDpFiCsOypTg',
    appId: '1:64654885784:ios:b0ea577dde19a4819ba1ed',
    messagingSenderId: '64654885784',
    projectId: 'expenses-app-a4b6b',
    storageBucket: 'expenses-app-a4b6b.firebasestorage.app',
    iosBundleId: 'com.example.expensesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAagTBxBMR1sQ7LL16UrT3wsNWr5CNZujc',
    appId: '1:64654885784:web:fbdc4a3222e7c5d39ba1ed',
    messagingSenderId: '64654885784',
    projectId: 'expenses-app-a4b6b',
    authDomain: 'expenses-app-a4b6b.firebaseapp.com',
    storageBucket: 'expenses-app-a4b6b.firebasestorage.app',
    measurementId: 'G-FRM8R61W5T',
  );

}